# Generated by Django 2.2 on 2020-08-19 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('tipoMaterial', models.CharField(max_length=30)),
                ('autor', models.CharField(max_length=30)),
                ('titulo', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoPersona', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=30)),
                ('telefono', models.ImageField(upload_to='')),
                ('numLibros', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bibliotec.Persona')),
                ('matricula', models.IntegerField()),
            ],
            bases=('bibliotec.persona',),
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bibliotec.Material')),
                ('editorial', models.CharField(max_length=30)),
            ],
            bases=('bibliotec.material',),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bibliotec.Persona')),
                ('numEmplado', models.IntegerField()),
            ],
            bases=('bibliotec.persona',),
        ),
        migrations.CreateModel(
            name='Revista',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bibliotec.Material')),
            ],
            bases=('bibliotec.material',),
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('idPrestamo', models.AutoField(primary_key=True, serialize=False)),
                ('fechaSalida', models.DateField()),
                ('fechaRegreso', models.DateField()),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotec.Material')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotec.Persona')),
            ],
        ),
    ]
