# Generated by Django 2.2 on 2020-08-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotec', '0002_auto_20200820_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, default='fotos_tapa/default.png', upload_to='fotos_tapa/'),
        ),
        migrations.AddField(
            model_name='material',
            name='anio',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('IN', 'En biblioteca'), ('BW', 'Prestado'), ('RQ', 'Pedido'), ('RV', 'Reservado')], default='En biblioteca', max_length=2),
        ),
    ]
